### ISSUE TITLE
`import pytorch_pfn_extras` fails when the file name is profile.py

### ISSUE THREAD

**Issue by dhgrs** [pfnet/pytorch-pfn-extras#109]
This is a bug report. `I'm using pytorch-pfn-extras==0.3.1 and I noticed that it fails import when the file name is profile.py. Here is the file.

```python
import pytorch_pfn_extras
```

When the file name is hoge.py, it doesn't cause any errors. But when it's profile.py, it cause an error.

```
$ /usr/bin/python3 /repo/profile.py
Traceback (most recent call last):
  File "/repo/profile.py", line 1, in <module>
    import pytorch_pfn_extras
  File "/usr/local/lib/python3.7/dist-packages/pytorch_pfn_extras/__init__.py", line 7, in <module>
    from pytorch_pfn_extras import training  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/pytorch_pfn_extras/training/__init__.py", line 6, in <module>
    from pytorch_pfn_extras.training import extensions  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/pytorch_pfn_extras/training/extensions/__init__.py", line 17, in <module>
    from pytorch_pfn_extras.training.extensions.print_report_notebook import PrintReportNotebook  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/pytorch_pfn_extras/training/extensions/print_report_notebook.py", line 3, in <module>
    from IPython.core.display import display
  File "/home/user/.local/lib/python3.7/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/home/user/.local/lib/python3.7/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/home/user/.local/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 28, in <module>
    from IPython.core.magics import (
  File "/home/user/.local/lib/python3.7/site-packages/IPython/core/magics/__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "/home/user/.local/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 24, in <module>
    import cProfile as profile
  File "/usr/lib/python3.7/cProfile.py", line 22, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'
```

**Comment by kmaehashi** [comment]
Thanks for the feedback! Unfortunately, this is by the design of Python and we can't do anything. I'd suggest renaming the script to avoid conflict with the standard module names.

https://docs.python.org/3/tutorial/modules.html#the-module-search-path
> The directory containing the script being run is placed at the beginning of the search path, ahead of the standard library path. This means that scripts in that directory will be loaded instead of modules of the same name in the library directory. This is an error unless the replacement is intended.

**Comment by dhgrs** [comment]
Ah, thank you for your time! It looks a trivial one now but I couldn't think of it last week.
