### ISSUE TITLE
SyntaxError when import `pytorch_pfn_extras.training.extensions` with py3.7

### ISSUE THREAD

**Issue by BingliangLI** [pfnet/pytorch-pfn-extras#236]
To reproduce: `from pytorch_pfn_extras.training import extensions as ppe_exts, triggers as ppe_triggers`

Error message:
```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-8e074eaf758b>", line 28, in <module>
    import pytorch_pfn_extras as ppe

  File "/opt/conda/lib/python3.7/site-packages/pytorch_pfn_extras/__init__.py", line 12, in <module>
    from pytorch_pfn_extras import training  # NOQA

  File "/opt/conda/lib/python3.7/site-packages/pytorch_pfn_extras/training/__init__.py", line 1, in <module>
    from pytorch_pfn_extras.training.extension import Extension  # NOQA

  File "/opt/conda/lib/python3.7/site-packages/pytorch_pfn_extras/training/extension.py", line 47
    trigger: 'TriggerLike' = 1, 'iteration'
                              ^
SyntaxError: invalid syntax
```
Environment:
Python 3.7.10, using pytorch-pfn-extras 0.4.3

pytorch-pfn-extras 0.4.1 works fine

BTW, thanks for all the great work!

**Comment by kmaehashi** [comment]
Thanks for reporting! We've just noticed that and released a hot-fix.
https://github.com/pfnet/pytorch-pfn-extras/releases/tag/v0.4.4
