### ISSUE TITLE
ppe.onnx.strip_large_tensor raises error with ONNX==1.9.0

### ISSUE THREAD

**Issue by sandman42292** [pfnet/pytorch-pfn-extras#268]
With ONNX==1.8.0, 
```
python3 -m pytorch_pfn_extras.onnx.strip_large_tensor --out_onnx_path stripped.onnx model.onnx
```
runs piecefully, but with ONNX==1.9.0, it raises error below.

```
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'pytorch_pfn_extras.onnx.strip_large_tensor' found in sys.modules after import of package 'pytorch_pfn_extras.onnx', but prior to execution of 'pytorch_pfn_extras.onnx.strip_large_tensor'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/pytorch_pfn_extras/onnx/strip_large_tensor.py", line 81, in <module>
    _strip_large_tensor_tool()
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/pytorch_pfn_extras/onnx/strip_large_tensor.py", line 77, in _strip_large_tensor_tool
    args.large_tensor_threshold)
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/pytorch_pfn_extras/onnx/strip_large_tensor.py", line 59, in _strip_large_tensor_tool_impl
    _strip_large_initializer_raw_data(onnx_model, large_tensor_threshold)
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/pytorch_pfn_extras/onnx/strip_large_tensor.py", line 53, in _strip_large_initializer_raw_data
    _strip_raw_data(init)
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/pytorch_pfn_extras/onnx/strip_large_tensor.py", line 41, in _strip_raw_data
    length=len(tensor.raw_data))
  File "/home/xxx/stript_test/venv/lib/python3.6/site-packages/onnx/external_data_helper.py", line 86, in set_external_data
    raise ValueError("Tensor " + tensor.name + "does not have raw_data field. Cannot set external data for this tensor.")
ValueError: Tensor Parameter5does not have raw_data field. Cannot set external data for this tensor.
```

**Comment by kmaehashi** [comment]
Fixed via #364
