### ISSUE TITLE
EOF Error in multiprocessing

### ISSUE THREAD

**Issue by masanorihirano** [pfnet/pytorch-pfn-extras#377]
After the upgrading of ppe==0.5.0, the following test code shows an EOF error.

Also under ppe==0.4.5, there is an issue that the last reported metric is not recorded on tensorbord (I mean the third `train/loss` and `val/loss` in the following code),
But, there is a workaround that is just adding time.sleep(1) before the end of the subprocess like the following.

However, under the new version of ppe, the following code fails completely, and I haven't found any workaround or fixing solution.

Does anyone have solutions?

```python
import multiprocessing as mp
import random
import time

import pytorch_pfn_extras as ppe
from torch.utils.tensorboard import SummaryWriter


def subprocess(num: int):
    ppe_extensions = [
        ppe.training.extensions.LogReport(),
        ppe.training.extensions.PlotReport(y_keys=["train/loss", "val/loss"], x_key="epoch",
                                           file_name="loss{}.png".format(num)),
    ]
    writer = ppe.writing.SimpleWriter(out_dir="save/logs-{}".format(num))
    manager = ppe.training.ExtensionsManager(models={}, optimizers={}, max_epochs=3,
                                             extensions=ppe_extensions, writer=writer, iters_per_epoch=1)
    tb_writer = SummaryWriter(log_dir="save/tensorboard-{}".format(num))

    @ppe.training.make_extension(trigger=(1, 'epoch'))
    def tensorboard_writer(manager):
        m = manager.observation
        tb_writer.add_scalars("loss", {'train/loss': m['train/loss'], 'val/loss': m['val/loss']}, manager.epoch)

    manager.extend(tensorboard_writer)

    for _ in range(3):
        with manager.run_iteration():
            ppe.reporting.report({"train/loss": random.random()})
            ppe.reporting.report({"val/loss": random.random()})
    time.sleep(1)
    return

def main():
    process = []
    for i in range(2):
        p = mp.Process(target=subprocess, args=(i,))
        process.append(p)
    for p in process:
        p.start()
    for p in process:
        p.join()
        p.close()


if __name__ == '__main__':
    main()
```

Result:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/*************/ppe-debug/.venv/lib/python3.9/site-packages/pytorch_pfn_extras/profiler/_time_summary.py", line 80, in _worker
    v = self._queue.get()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/*************/ppe-debug/.venv/lib/python3.9/site-packages/pytorch_pfn_extras/profiler/_time_summary.py", line 80, in _worker
    v = self._queue.get()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

**Comment by masanorihirano** [comment]
Thank you so much, everyone involved in this issue!
