### ISSUE TITLE
AttributeError is raised in pfto exporter

### ISSUE THREAD

**Issue by asi1024** [pfnet/pytorch-pfn-extras#513]
- reproducer
```py
import torch
from pytorch_pfn_extras.onnx import pfto_exporter


class Model(torch.nn.Module):

    def forward(self, x):
        return torch.sum(x == 1, dtype=torch.float32)


model = Model()
input = torch.rand((20,))
ex = pfto_exporter.export.export(
    model, input, f='out',
    input_names=['x'], output_names=['y'],
)
```

- traceback
```
Traceback (most recent call last):
  File "XXX/pytorch-pfn-extras/run.py", line 13, in <module>
    ex = pfto_exporter.export.export(
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 880, in export
    ex = _Exporter(model, inputs=args, **kwargs)
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 180, in __init__
    self._convert()
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 856, in _convert
    self.model: onnx.ModelProto = self.generate_onnx()
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 730, in generate_onnx
    self.generate_onnx_node(self.g, n)
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 543, in generate_onnx_node
    self.run_symbolic_function(g, n, f)
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 506, in run_symbolic_function
    sym_nodes: List[torch._C.Node] = list_added_nodes()
  File "XXX/pytorch-pfn-extras/pytorch_pfn_extras/onnx/pfto_exporter/export.py", line 496, in list_added_nodes
    ret.add(i.node())
AttributeError: 'NoneType' object has no attribute 'node'
```

cc: @take-cheeze

**Comment by take-cheeze** [comment]
This seems to be caused by bug in torch.onnx: https://github.com/pytorch/pytorch/pull/64289

**Comment by asi1024** [comment]
I confirmed that the above script works without error with torch==1.11.
